# Generated by Django 2.1.1 on 2018-10-06 12:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TD_DATA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FACTORY', models.CharField(max_length=50)),
                ('CATEGORY', models.CharField(max_length=50)),
                ('VALUE', models.DecimalField(decimal_places=2, max_digits=8)),
                ('DATA_DATE', models.CharField(max_length=50)),
                ('UPDATE_TIME', models.DateTimeField(default=django.utils.timezone.now)),
                ('IP_ADDRESS', models.CharField(max_length=50)),
            ],
        ),
    ]
